### ISSUE TITLE
Question - Is it possible to conditionally chain ParamBuilder class methods?

### ISSUE THREAD

**Issue by dylanlarrivee** [BitPatty/imgproxy-url-builder#167]
Hi,
I am hoping to conditionally chain some of the pb() class methods something like this :

```
 const optimizeUrlParams = pb();
 if (resizeType || width || height) {
    const resizeOptions = {resizeType, width, height};
    optimizeUrlParams.resize(resizeOptions);
  }
  optimizeUrlParams.blur(10);
  optimizeUrlParams.build({
    path: srcPath,
    baseUrl: 'http://localhost:4640',
    signature: {
      key: 'key',
      salt: 'salt'
    }
  });

```
I can see that the `.resize` and `.blur` get added to the class but the `.build` does not seem to work as expected and returns an object. Do you know if there is a way for it to work like this?

Thanks!

**Comment by BitPatty** [comment]
I haven't tried to reproduce your issue yet and you're right, adding these modifiers conditionally should work the way you did it. 

Just to clarify:

`.build()` returns a string, but does not modify the instance itself. The modifiers (`.blur`, `.resize`) do however. This is intended behavior to allow for applying the same builder instance on different images.

Are you expecting `optimizeUrlParams` to be a string after `.build()`?

e.g.

```diff
 const optimizeUrlParams = pb();
 if (resizeType || width || height) {
    const resizeOptions = {resizeType, width, height};
    optimizeUrlParams.resize(resizeOptions);
  }
  optimizeUrlParams.blur(10);
-  optimizeUrlParams.build({
+  // myUrl holds the build result
+  const myUrl = optimizeUrlParams.build({
    path: srcPath,
    baseUrl: 'http://localhost:4640',
    signature: {
      key: 'key',
      salt: 'salt'
    }
  });
```

**Comment by dylanlarrivee** [comment]
Ah that makes sense, I was thinking that `.build()` modified the instance itself. I dont need `optimizeUrlParam` to be a string but rather just have a way to access that string which I think your example will do. I will play around with that. Thanks!
