### ISSUE TITLE
Change Signature Size

### ISSUE THREAD

**Issue by keeeparis** [BitPatty/imgproxy-url-builder#369]
Hi,
Is it possible to add support for changing signature size to different value? For example, 8. As I understand, right now is 32.

**Comment by BitPatty** [comment]
Sorry, been away for a while. Shortening the signature size is currently not built in, but I'll look into it

**Comment by keeeparis** [comment]
@BitPatty Thanks!

**Comment by BitPatty** [comment]
You can now specify the size in the signature options in 1.2.1

**Comment by keeeparis** [comment]
That is awesome!
